### ISSUE TITLE
Transform's dependent files not watched

### ISSUE THREAD

**Issue by jiaweihli** [benbria/uber-watchify#8]
If the cache is valid, no handlers are set up on a transform's dependent files.
Also has no way of detecting if a transform's dependent files have changed.

This functionality is really useful for transforming LESS - see https://github.com/wilson428/node-lessify/pull/21.

**Comment by calvinwiebe** [comment]
Hey @jiaweihli. I imagine `node-lessify` would also not work in normal `watchify` until wilson428/node-lessify#21 is merged, no?

When you say _transform's dependent files_, I assume you are meaning the `@import`'s of a LESS file are not watched?

**Comment by jiaweihli** [comment]
Right, but this applies to any transform that does `emit('file', ...)`.

**Comment by calvinwiebe** [comment]
Ah! I think I see what you mean now. Since a custom transform's deps - that are imported outside the scope of `require` - are not tracked in the `browserify` dependency graph, they are also not propagated to the `uber-watchify` cache file. Yes. 

This is an interesting problem. Keeping track of these non-require dependencies in the dep graph is really something for `browserify` or `watchify`. However, `uber-watchify` does break the ability to rebuild on the deps change. At the very least, I could change it so `uber-watchify` would still see the change, even if it does not cache the source of the deps in the graph. 

The workaround is to just `touch` the entry `.less` file, as it would be tracked via the `require` dep graph. i.e. `require('something.less'`. Touching `something.less` would trigger a rebuild. 

I will look into it. Thanks.
